import type { ServiceDetail } from "@/lib/types";

export const SERVICES: ServiceDetail[] = [
  {
    id: "rag",
    badge: "Knowledge Intelligence",
    icon: "database",
    title: "RAG Agents",
    paragraphs: [
      "Retrieval-Augmented Generation (RAG) agents connect your documents, databases, and knowledge bases to a conversational AI. Your team can ask questions in plain English and get instant, accurate answers — no more digging through folders.",
      "Whether it's a 10,000-page policy library or a live database, we build RAG pipelines that are accurate, fast, and fully private.",
    ],
    features: [
      "Document Q&A (PDFs, Word, Excel, SharePoint)",
      "Multi-source vector search with re-ranking",
      "Citation-backed answers for compliance",
      "Private deployment — your data stays yours",
      "Slack, Teams, or web chat integration",
      "Powered by LangChain + Pinecone / Chroma",
    ],
    cta: "Get a RAG Agent",
  },
  {
    id: "voice",
    badge: "Hands-Free Intelligence",
    icon: "mic",
    title: "Voice AI Agents",
    reverse: true,
    paragraphs: [
      "Our Voice AI agents listen, understand context, and take action — all in real time. From call centers to internal ops tools, we build voice solutions that feel natural and work reliably at scale.",
      "Powered by Deepgram STT and ElevenLabs TTS, our agents handle complex multi-turn conversations and can trigger backend workflows with a spoken command.",
    ],
    features: [
      "Real-time speech-to-text and response",
      "Multi-turn contextual conversations",
      "Voice-triggered workflow automation",
      "Call center & customer support agents",
      "20+ language support with auto-detection",
      "<500ms perceived response latency",
    ],
    cta: "Build a Voice Agent",
  },
  {
    id: "claude",
    badge: "Anthropic Claude",
    icon: "brain",
    title: "Claude AI Agents",
    paragraphs: [
      "We build production-grade AI solutions using Anthropic's Claude API — the world's most capable and safest AI models. Claude's 200K context window and superior reasoning make it perfect for complex document analysis, multi-step tasks, and enterprise deployments.",
      "From customer-facing chatbots to internal ops assistants, Claude handles it all with constitutional safety built in — never hallucinating, always citing sources.",
    ],
    features: [
      "Claude Sonnet 4.6 & Opus 4.6 — latest models",
      "200,000 token context — analyze entire codebases",
      "Tool use & agentic multi-step task execution",
      "Customer chat agents with human escalation",
      "Document intelligence with source citations",
      "Enterprise safety, GDPR-compliant, private deploy",
      "Slack, Teams, web widget integration",
    ],
    cta: "Build with Claude",
  },
  {
    id: "n8n",
    badge: "n8n Automation",
    icon: "settings",
    title: "n8n Workflows",
    reverse: true,
    paragraphs: [
      "We're n8n specialists. As the world's most powerful self-hosted automation platform, n8n gives you complete control over your data while connecting 400+ apps and services into seamless pipelines.",
      "From simple email-to-CRM flows to complex AI-augmented multi-step workflows with error handling, retries, and real-time monitoring — we build it right.",
    ],
    features: [
      "Self-hosted or n8n Cloud deployment",
      "400+ native integrations (Slack, HubSpot, Gmail...)",
      "AI nodes — Claude, OpenAI, Anthropic built-in",
      "Webhook triggers, cron schedules, real-time events",
      "Error branches, retry logic, failure notifications",
      "Custom code nodes (Python / JavaScript)",
      "Full workflow documentation & handover",
    ],
    cta: "Build n8n Workflows",
  },
  {
    id: "sharepoint",
    badge: "Microsoft Ecosystem",
    icon: "layers",
    title: "SharePoint Integration",
    paragraphs: [
      "We embed AI directly into your Microsoft 365 environment — automating document workflows, enabling intelligent search, and reducing the manual overhead of SharePoint management.",
      "Our agents connect SharePoint to Teams, Outlook, and your CRM — creating a unified, intelligent workspace.",
    ],
    features: [
      "AI-powered document search across sites",
      "Automated approval & review workflows",
      "Teams bot for SharePoint queries",
      "Metadata tagging & content classification",
      "Onboarding & HR document automation",
      "Microsoft Graph API — OAuth 2.0 secure",
    ],
    cta: "Automate SharePoint",
  },
  {
    id: "automation",
    badge: "Time Savings at Scale",
    icon: "zap",
    title: "Workflow Automation",
    reverse: true,
    paragraphs: [
      "We design and build automation pipelines that eliminate repetitive manual work. Using n8n, Make (Integromat), and custom AI agents, we connect your apps and let data flow without human intervention.",
      "Our clients typically reclaim 20–60 hours per week through targeted automation.",
    ],
    features: [
      "End-to-end business process automation",
      "CRM, email, and calendar integrations",
      "Data extraction, transformation & reporting",
      "Trigger-based notifications & actions",
      "n8n, Make, Zapier, and custom pipelines",
    ],
    cta: "Automate My Workflows",
  },
  {
    id: "custom",
    badge: "Built for You",
    icon: "bot",
    title: "Custom AI Agents",
    paragraphs: [
      "Sometimes off-the-shelf tools don't cut it. We design and build fully custom AI agents tailored to your exact industry, workflows, and data — from legal research assistants to manufacturing quality agents.",
    ],
    features: [
      "Industry-specific agent design",
      "Multi-agent orchestration systems",
      "Tool-use and API-calling agents",
      "Long-running autonomous task agents",
      "Fine-tuned models on your data",
    ],
    cta: "Build Custom Agent",
  },
  {
    id: "consulting",
    badge: "Strategic Guidance",
    icon: "chart-line",
    title: "AI Consulting",
    reverse: true,
    paragraphs: [
      "Not sure where to start with AI? We audit your workflows, identify high-ROI automation opportunities, and deliver a clear roadmap — whether you build with us or your internal team.",
    ],
    features: [
      "Workflow & process audit",
      "AI readiness assessment",
      "ROI modeling & prioritization",
      "Vendor & tool selection guidance",
      "Implementation roadmap & timeline",
    ],
    cta: "Book a Consultation",
  },
];
