import type { Metadata } from "next";
import { AGENCY } from "./constants/agency";
import { ASSETS } from "./assets";

const siteName = AGENCY.name;
const defaultDescription =
  "AI agents that answer your calls, reply to WhatsApp and email, and clear repetitive admin around the clock — plus instant answers from your own documents.";

/**
 * The share card generated by `app/opengraph-image.tsx`, referenced explicitly.
 *
 * It has to be explicit. Metadata objects across segments are merged
 * *shallowly* and duplicate keys are replaced wholesale — so the moment a page
 * returns its own `openGraph` object, it discards whatever the file convention
 * injected. Spreading this into every page keeps the card attached, which is
 * the pattern Next's own docs recommend.
 *
 * `metadataBase` turns the relative path into an absolute URL.
 */
const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: siteName,
} as const;

export const rootMetadata: Metadata = {
  metadataBase: new URL(AGENCY.domain),
  title: {
    default: `${siteName} | Intelligent AI Automation`,
    template: `%s | ${siteName}`,
  },
  description: defaultDescription,
  keywords: [
    "AI automation",
    "RAG agents",
    "Voice AI",
    "n8n workflows",
    "SharePoint integration",
    "Claude AI",
    "enterprise automation",
  ],
  authors: [{ name: siteName }],
  creator: siteName,
  robots: { index: true, follow: true },
  icons: {
    icon: [{ url: ASSETS.favicon, type: "image/svg+xml" }],
    shortcut: [ASSETS.favicon],
    apple: [{ url: ASSETS.appleIcon, type: "image/svg+xml" }],
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: AGENCY.domain,
    siteName,
    title: `${siteName} | Intelligent AI Automation`,
    description: defaultDescription,
    images: [OG_IMAGE],
  },
  twitter: {
    card: "summary_large_image",
    title: `${siteName} | Intelligent AI Automation`,
    description: defaultDescription,
    images: [OG_IMAGE.url],
  },
  verification: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION
    ? { google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION }
    : undefined,
};

export function createPageMetadata({
  title,
  description,
  path,
}: {
  title: string;
  description: string;
  path: string;
}): Metadata {
  const url = `${AGENCY.domain}${path}`;
  return {
    title,
    description,
    alternates: { canonical: url },
    openGraph: {
      title,
      description,
      url,
      images: [OG_IMAGE],
    },
    twitter: {
      // `card` must be repeated: this object replaces the root's twitter
      // object rather than merging into it, so omitting it silently
      // downgrades every page to a small "summary" card.
      card: "summary_large_image",
      title,
      description,
      images: [OG_IMAGE.url],
    },
  };
}

export const SITEMAP_ROUTES = [
  { path: "/", priority: 1, changeFrequency: "weekly" as const },
  { path: "/voice-agents", priority: 0.9, changeFrequency: "monthly" as const },
  { path: "/services", priority: 0.9, changeFrequency: "monthly" as const },
  { path: "/about", priority: 0.8, changeFrequency: "monthly" as const },
  { path: "/contact", priority: 0.9, changeFrequency: "weekly" as const },
  { path: "/privacy", priority: 0.5, changeFrequency: "yearly" as const },
  { path: "/terms", priority: 0.5, changeFrequency: "yearly" as const },
];
